### ISSUE TITLE
OSX Build?

### ISSUE THREAD

**Issue by iandanforth** [spook/sshping#13] opened 2018-11-06 22:27 UTC
I wondered if you'd ever built this on OSX. I don't find a 'libssh-dev' or 'libssh-devel' easily available for the platform.

**Comment by spook** [comment] 2018-11-09 16:09
Hello @iandanforth,
Sorry I don't have a Mac to do this.  But I did find this link to get [libssh](http://macappstore.org/libssh/) tho this is the binary not the devel package.  The -dev package is essentially just the headers and a repeat of the library binaries so the compiles work.  Perhaps you could grab the headers from [libssh's github](https://github.com/substack/libssh).  Here's the listing of the libssh-dev package on a Debian system, if it helps:
```
$ dpkg -L libssh-dev
/.
/usr
/usr/include
/usr/include/libssh
/usr/include/libssh/callbacks.h
/usr/include/libssh/legacy.h
/usr/include/libssh/libssh.h
/usr/include/libssh/libsshpp.hpp
/usr/include/libssh/server.h
/usr/include/libssh/sftp.h
/usr/include/libssh/ssh2.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libssh.a
/usr/lib/x86_64-linux-gnu/libssh_threads.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/libssh.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libssh_threads.pc
/usr/share
/usr/share/doc
/usr/share/doc/libssh-dev
/usr/share/doc/libssh-dev/copyright
/usr/lib/x86_64-linux-gnu/libssh.so
/usr/lib/x86_64-linux-gnu/libssh_threads.so
/usr/share/doc/libssh-dev/changelog.Debian.gz
```

**Comment by ericcurtin** [comment] 2018-11-15 06:16
@MarcinZukowski was building on OSX see #10 he might be of some help. It should still build as this has been built this on gcc, clang and msvc recently. So the compiler support should be there provided all the libraries are the same.

Might be time for some Travis CI and AppVeyor to get some Linux, OSX and Windows builds going to ensure we maintain compatibility.

**Comment by MarcinZukowski** [comment] 2018-11-15 19:55
Just install MacPorts and then do `sudo port install libsssh`

**Comment by ericcurtin** [comment] 2018-11-21 00:01
We also compiled against vcpkg libssh library on Windows. You might be able to pull an OSX package using vcpkg also

**Comment by spook** [comment] 2018-12-06 17:02
@iandanforth Closing this as it seems you have options now.

**Closed by spook** 2018-12-06 17:02 UTC

**Comment by guoquan** [comment] 2020-11-11 06:13
Hi, here is how I came through this issue.

#### `libssh`

Homebrew installs `libssh` with headers. So just do:
```
brew install libssh
```
The issue is the headers are not located under the same directory on OSX as on Linux.
They are under `/usr/local/include/libssh/` instead of `/usr/include/libssh/`.
I PR #25  to add the alternative path to headers in Makefile.

#### `ProxyJump`
Another note is that this project is built on `libssh`, hence `ProxyJump` is not supported. In case you need a hop, use `ProxyCommand` instead.

Hope this will help anyone who wants to play this on OSX.
